# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d58264b20d6ced0a92f38a9e1df2fb9471210f782bdb0310c51c0aa3375d00269e93afb549f1c786fb982b47d8812c8900a5f502cb35137ba091a60d284c1be

test:
  secret_key_base: 735be74ecdb96ce032d282da088c44118bf89790f752220d6e71448994417b1fd62572df463d44a0317f86f763c9534e2f30715d2edf04e29e2a231bff729fcb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
